const factObj = {
  identifier: 'string',
  isTrue: 'boolean',
  composedFacts: 'arrayRef',
  validity: 'string',
  withDelay: 'string',
  makesTrue: 'arrayRef',
  withIPEntity: 'ref',
  partOf: 'arrayRef',
  languages: 'array',
  maxLength: 'string',
  matchesFormatComplianceProfile: 'string',
  aspectRatio: 'string',
  audioFormat: 'string',
  format: 'string',
  maxBitrate: 'number',
  maxLines: 'number',
  minBitrate: 'number',
  minLines: 'number',
  videoFormat: 'string',
  numberOfRuns: 'number',
  numberOfRepetitions: 'number',
  servicesAndChannels: 'array',
  countries: 'array',
  afterDate: 'string',
  beforeDate: 'string',
  extra: 'map',
  // personal data handling
  restriction: 'string',
  hasDataController: 'ref',
  hasDataSubject: 'ref',
  hasLegalBasis: 'arrayRef',
  hasPersonalData: 'arrayRef',
  hasPersonalDataHandling: 'arrayRef',
  hasProcessing: 'arrayRef',
  hasPurpose: 'arrayRef',
  hasRecipient: 'arrayRef',
  hasRight: 'arrayRef',
  hasRisk: 'arrayRef',
  hasTechnicalOrganisationalMeasure: 'arrayRef',
  hasConsentNotice: 'string',
  hasExpiry: 'string',
  hasExpiryCondition: 'string',
  hasExpiryTime: 'string',
  hasProvisionBy: 'string',
  hasProvisionByJustification: 'string',
  hasProvisionMethod: 'string',
  hasProvisionTime: 'string',
  hasWithdrawalBy: 'string',
  hasWithdrawalByJustification: 'string',
  hasWithdrawalMethod: 'string',
  hasWithdrawalTime: 'string',
  isExplicit: 'boolean',
};

module.exports = {
  factObj,
};
